using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;

// Generates the sim's data classes from the collections' schemas: one file per collection in
// Assets/Codigames/Kingdom/Data/Generated. Run it after a schema changes:
//   dotnet run --project Tools/Codegen
// A collection is a MAP of entries by id, an ordered LIST of entries, or a FORM of settings groups,
// read from the shape of its game file.
public static class Program
{
    // The name of one entry of each collection (its noun).
    private static readonly Dictionary<string, string> NOUNS = new()
    {
        ["adjacency"] = "AdjacencyRule", ["artifacts"] = "Artifact", ["banners"] = "Banner",
        ["buildings"] = "Building", ["combat"] = "Combat", ["currencies"] = "Currency",
        ["economy"] = "Economy", ["exploration"] = "Exploration", ["garrisons"] = "Garrison",
        ["goods"] = "Good", ["harvest"] = "HarvestSource", ["heroLadder"] = "HeroLadderSettings",
        ["heroes"] = "Hero", ["items"] = "Item", ["monetization"] = "Monetization", ["quests"] = "Quest",
        ["relics"] = "RelicRules", ["scenes"] = "Scene", ["social"] = "Social", ["speakers"] = "Speaker",
        ["store"] = "Product", ["survey"] = "SurveySettings", ["terrain"] = "Terrain", ["tutorial"] = "Tutorial",
        ["units"] = "Unit", ["unlocks"] = "Unlock", ["villains"] = "Villain", ["world"] = "WorldSettings",
    };

    public static int Main(string[] args)
    {
        var root = FindProjectRoot();
        var dataDir = Path.Combine(root, "Assets/Data");
        var outDir = Path.Combine(root, "Assets/Codigames/Kingdom/Data/Generated");
        Directory.CreateDirectory(outDir);

        var written = new HashSet<string>();
        var collections = new StringBuilder();

        foreach (var schemaPath in Directory.GetFiles(Path.Combine(dataDir, "Schema"), "*.json").OrderBy(p => p, StringComparer.Ordinal))
        {
            var id = Path.GetFileNameWithoutExtension(schemaPath);
            if (!NOUNS.TryGetValue(id, out var noun))
            {
                Console.Error.WriteLine($"No noun for collection '{id}': add it to NOUNS.");
                return 1;
            }

            var schema = JObject.Parse(File.ReadAllText(schemaPath));
            var game = JToken.Parse(File.ReadAllText(Path.Combine(dataDir, "Game", id + ".json")));
            var shape = ShapeOf(schema, game);

            var classes = new List<string>();
            var entryType = noun + "Data";
            EmitClass(entryType, (JObject)schema["fields"], classes, $"One {noun.ToLowerInvariant()}, as {id}.json holds it.");

            var file = new StringBuilder();
            file.AppendLine("// <auto-generated>");
            file.AppendLine($"// From Assets/Data/Schema/{id}.json by Tools/Codegen. Do not edit: change the schema and");
            file.AppendLine("// run `dotnet run --project Tools/Codegen`.");
            file.AppendLine("// </auto-generated>");
            file.AppendLine("using System.Collections.Generic;");
            file.AppendLine("using Newtonsoft.Json;");
            file.AppendLine();
            file.AppendLine("namespace Codigames.Kingdom.Data");
            file.AppendLine("{");
            file.Append(string.Join("\n", classes));
            file.AppendLine("}");

            var outPath = Path.Combine(outDir, entryType + ".g.cs");
            File.WriteAllText(outPath, file.ToString().Replace("\r\n", "\n"));
            written.Add(Path.GetFileName(outPath));

            var rootType = shape switch
            {
                "map" => $"Dictionary<string, {entryType}>",
                "list" => $"List<{entryType}>",
                _ => entryType,
            };
            collections.AppendLine($"        [JsonProperty(\"{id}\")] public {rootType} {Pascal(id)} {{ get; set; }}");
            Console.WriteLine($"{id,-14} {shape,-4} -> {entryType}");
        }

        var registry = new StringBuilder();
        registry.AppendLine("// <auto-generated>");
        registry.AppendLine("// By Tools/Codegen from the collections in Assets/Data/Game. Do not edit.");
        registry.AppendLine("// </auto-generated>");
        registry.AppendLine("using System.Collections.Generic;");
        registry.AppendLine("using Newtonsoft.Json;");
        registry.AppendLine();
        registry.AppendLine("namespace Codigames.Kingdom.Data");
        registry.AppendLine("{");
        registry.AppendLine("    // Every collection, as its game file holds it: a map of entries by id, an ordered list, or a form.");
        registry.AppendLine("    public sealed class Collections");
        registry.AppendLine("    {");
        registry.Append(collections);
        registry.AppendLine("    }");
        registry.AppendLine("}");
        File.WriteAllText(Path.Combine(outDir, "Collections.g.cs"), registry.ToString().Replace("\r\n", "\n"));
        written.Add("Collections.g.cs");

        foreach (var stale in Directory.GetFiles(outDir, "*.g.cs").Where(p => !written.Contains(Path.GetFileName(p))))
        {
            File.Delete(stale);
            if (File.Exists(stale + ".meta")) File.Delete(stale + ".meta");
            Console.WriteLine($"removed {Path.GetFileName(stale)}");
        }

        return 0;
    }

    private static string ShapeOf(JObject schema, JToken game)
    {
        if (game is JArray) return "list";
        var fields = (JObject)schema["fields"];
        return ((JObject)game).Properties().All(p => fields.ContainsKey(p.Name)) ? "form" : "map";
    }

    private static void EmitClass(string name, JObject fields, List<string> classes, string comment)
    {
        var body = new StringBuilder();
        body.AppendLine($"    // {comment}");
        body.AppendLine($"    public sealed class {name}");
        body.AppendLine("    {");

        foreach (var field in fields.Properties())
        {
            var type = TypeOf(name + Pascal(field.Name), (JObject)field.Value, classes);
            body.AppendLine($"        [JsonProperty(\"{field.Name}\")] public {type} {Pascal(field.Name)} {{ get; set; }}");
        }

        body.AppendLine("    }");
        classes.Insert(0, body.ToString());
    }

    private static string TypeOf(string ownerName, JObject field, List<string> classes)
    {
        var nullable = field.Value<bool?>("nullable") == true;
        var type = field.Value<string>("type");

        switch (type)
        {
            case "int":
            case "float":
            case "unknown":
                return nullable || type == "unknown" ? "double?" : "double";
            case "bool":
                return nullable ? "bool?" : "bool";
            case "text":
                return "string";
            case "list":
                return $"List<{TypeOf(ownerName + "Entry", (JObject)field["of"], classes)}>";
            case "map":
                return $"Dictionary<string, {TypeOf(ownerName + "Value", (JObject)field["of"], classes)}>";
            case "object":
                if (field["fields"] is not JObject nested) return "Newtonsoft.Json.Linq.JObject";
                EmitClass(ownerName, nested, classes, "Part of the data above.");
                return ownerName;
            default:
                throw new InvalidOperationException($"Unknown schema type '{type}' at {ownerName}.");
        }
    }

    private static string Pascal(string name)
        => string.IsNullOrEmpty(name) ? name : char.ToUpperInvariant(name[0]) + name.Substring(1);

    private static string FindProjectRoot()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir != null && !Directory.Exists(Path.Combine(dir.FullName, "Assets/Codigames"))) dir = dir.Parent;
        return dir?.FullName ?? throw new InvalidOperationException("Run from inside the Unity project.");
    }
}
